deploy:  
  provider: azure_web_apps
  username: disapp
  password: vdsi@123
  site: loginsvc

language: csharp
solution: CustDisApp.sln
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.0" CustDisApp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CustDisApp.Tests/bin/Release/CustDisApp.Tests.dll
sudo: required